package models

// ShapeType Geometric shape type.
type ShapeType string

// List of ShapeType
const (
	SHAPETYPE_SQUARE              ShapeType = "SQUARE"
	SHAPETYPE_ELLIPSE             ShapeType = "ELLIPSE"
	SHAPETYPE_ROUNDED_RECTANGLE   ShapeType = "ROUNDED_RECTANGLE"
	SHAPETYPE_DIAMOND             ShapeType = "DIAMOND"
	SHAPETYPE_TRIANGLE_UP         ShapeType = "TRIANGLE_UP"
	SHAPETYPE_TRIANGLE_DOWN       ShapeType = "TRIANGLE_DOWN"
	SHAPETYPE_PARALLELOGRAM_RIGHT ShapeType = "PARALLELOGRAM_RIGHT"
	SHAPETYPE_PARALLELOGRAM_LEFT  ShapeType = "PARALLELOGRAM_LEFT"
	SHAPETYPE_ENG_DATABASE        ShapeType = "ENG_DATABASE"
	SHAPETYPE_ENG_QUEUE           ShapeType = "ENG_QUEUE"
	SHAPETYPE_ENG_FILE            ShapeType = "ENG_FILE"
	SHAPETYPE_ENG_FOLDER          ShapeType = "ENG_FOLDER"
	SHAPETYPE_TRAPEZOID           ShapeType = "TRAPEZOID"
	SHAPETYPE_PREDEFINED_PROCESS  ShapeType = "PREDEFINED_PROCESS"
	SHAPETYPE_SHIELD              ShapeType = "SHIELD"
	SHAPETYPE_DOCUMENT_SINGLE     ShapeType = "DOCUMENT_SINGLE"
	SHAPETYPE_DOCUMENT_MULTIPLE   ShapeType = "DOCUMENT_MULTIPLE"
	SHAPETYPE_MANUAL_INPUT        ShapeType = "MANUAL_INPUT"
	SHAPETYPE_HEXAGON             ShapeType = "HEXAGON"
	SHAPETYPE_CHEVRON             ShapeType = "CHEVRON"
	SHAPETYPE_PENTAGON            ShapeType = "PENTAGON"
	SHAPETYPE_OCTAGON             ShapeType = "OCTAGON"
	SHAPETYPE_STAR                ShapeType = "STAR"
	SHAPETYPE_PLUS                ShapeType = "PLUS"
	SHAPETYPE_ARROW_LEFT          ShapeType = "ARROW_LEFT"
	SHAPETYPE_ARROW_RIGHT         ShapeType = "ARROW_RIGHT"
	SHAPETYPE_SUMMING_JUNCTION    ShapeType = "SUMMING_JUNCTION"
	SHAPETYPE_OR                  ShapeType = "OR"
	SHAPETYPE_SPEECH_BUBBLE       ShapeType = "SPEECH_BUBBLE"
	SHAPETYPE_INTERNAL_STORAGE    ShapeType = "INTERNAL_STORAGE"
)

// All allowed values of ShapeType enum
var AllowedShapeTypeEnumValues = []ShapeType{
	"SQUARE",
	"ELLIPSE",
	"ROUNDED_RECTANGLE",
	"DIAMOND",
	"TRIANGLE_UP",
	"TRIANGLE_DOWN",
	"PARALLELOGRAM_RIGHT",
	"PARALLELOGRAM_LEFT",
	"ENG_DATABASE",
	"ENG_QUEUE",
	"ENG_FILE",
	"ENG_FOLDER",
	"TRAPEZOID",
	"PREDEFINED_PROCESS",
	"SHIELD",
	"DOCUMENT_SINGLE",
	"DOCUMENT_MULTIPLE",
	"MANUAL_INPUT",
	"HEXAGON",
	"CHEVRON",
	"PENTAGON",
	"OCTAGON",
	"STAR",
	"PLUS",
	"ARROW_LEFT",
	"ARROW_RIGHT",
	"SUMMING_JUNCTION",
	"OR",
	"SPEECH_BUBBLE",
	"INTERNAL_STORAGE",
}
